name: greencat
description: A port of Redux to Dart, including Redux Thunk and a simple Logger.
version: 0.2.0
author: Alexei Diaz <alexei.eleusis@gmail.com>
homepage: https://github.com/alexeieleusis/greencat

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  logging: ">=0.11.3 <0.12.0"
  tuple: ">=1.0.1 <2.0.0"

dev_dependencies:
  test: '>=1.5.1 <2.0.0'
  todo_list:
    path: testing/todo_list
