name: greencat
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Alexei Eleusis Díaz Vera <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  logging: '^0.11.3'
  tuple: '1.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  todo_list:
    path: testing/todo_list
