name: todo_list
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Alexei Eleusis Díaz Vera <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  greencat:
    path: ../..
  tuple: ^1.0.1

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
