name: 'todo_list_butterlfy'
version: 0.0.1
description: The todo list app implemented with Butterfly and greencat.
#author: Alexei Eleusis Díaz Vera <alexei.eleusis@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  butterfly: '0.0.2'
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  tuple: ">=1.0.0 <2.0.0"
  todo_list:
    path: ../../testing/todo_list
  greencat:
    path: ../..

transformers:
- dart_to_js_script_rewriter
