name: todo_list_flutter
description: A new flutter project.
dependencies:
  flutter:
    sdk: flutter
  todo_list:
    path: ../../testing/todo_list
  greencat:
    path: ../..

flutter:
  uses-material-design: true