name: todo_list_flutter
description: A new flutter project.
dependencies:
  flutter:
    path: ../../../flutter/packages/flutter
  todo_list:
    path: ../../testing/todo_list
  greencat:
    path: ../..
